# GitHub Pages configuration for CV
title: "Aaron J. Celestian, Ph.D. -- Curriculum Vitae"
description: "Research focused on understanding how minerals interact with their environments and living systems"
author: "Aaron J. Celestian"

# Use a clean, professional theme
theme: minima

# GitHub Pages settings
github_username: aaroncelestian
repository: CV

# Customize the theme
minima:
  skin: classic
  
# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Markdown settings
markdown: kramdown
highlighter: rouge

# SEO settings
lang: en-US

# Show excerpts on homepage
show_excerpts: false 
